apiVersion: v2
name: github-actions-runner-operator
description: A Helm chart for the github action runner operator.
keywords:
  - github
  - action runner
  - operator
  - ci
  - agent
home: https://github.com/evryfs/github-actions-runner-operator/
sources:
  - https://github.com/evryfs/github-actions-runner-operator/
  - https://github.com/evryfs/helm-charts/
maintainers:
  - name: davidkarlsen
    email: david.karlsen@evry.com
    url: https://github.com/davidkarlsen/
icon: https://media-exp1.licdn.com/dms/image/C4D0BAQFZ80eOhCewVw/company-logo_200_200/0?e=2159024400&v=beta&t=XFbeA46Og-bBC5Th2aFMwXfB1FssEqN5lx-hKraJuAg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.3.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: v0.6.0

kubeVersion: ">=1.16"
