apiVersion: v1
name: mcrouter
home: https://github.com/facebook/mcrouter
version: 0.0.12
appVersion: 0.40.0
description: Mcrouter is a memcached protocol router for scaling memcached deployments.
sources:
- https://github.com/facebook/mcrouter
- https://github.com/evryfs/docker-mcrouter
maintainers:
- name: davidkarlsen
  email: david@davidkarlsen.com
engine: gotpl
