## Container image
image: quay.io/evryfs/docker-mcrouter:0.40.0-4

## Memcached chart parameters
memcached:
  ## Use replicaset and HA
  architecture: high-availability
  ## If true, the Memcached chart will be installed as a dependency
  enabled: true
  ## Number of Memcached replicas
  replicaCount: 2

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 256m
    memory: 512Mi

nodeSelector: {}

service:
  clusterIP: None
  annotations: {}

## Parameters for the mcrouter command
mcrouterCommandParams:
  port: 5000

  ## Pass a custom JSON config, if not specified one will be generated per the number of memcached replicas
  ## https://github.com/facebook/mcrouter/wiki/Config-Files
  # configFile:

## Pod controller. Possible values: "daemonset", "statefulset".
controller: "daemonset"

clusterSuffix: cluster.local

## Values for the daemonset controller
daemonset:
  ## Host port for the mcrouter pod
  hostPort: 5000

## Values for the statefulset controller
statefulset:
  ## Number of replicas
  replicas: 1
  ## Select AntiAffinity as either hard or soft, default is hard
  antiAffinity: "hard"

exporter:
  enabled: false
  image:
    repository: quay.io/dev25/mcrouter_exporter
    tag: 0.1.0
  service:
    port: 9442
  resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
