{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" . }}-frontend
  labels: {{- include "common.labels.standard" . | nindent 4 }}
{{- end -}}
